name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r ./requirements.txt
        pip3 install flake8 pycodestyle isort mypy black

    - name: flake8
      if: always()
      run: source .venv/bin/activate && flake8 .

    - name: pycodestyle
      if: always()
      run: source .venv/bin/activate && pycodestyle .

    - name: isort
      if: always()
      run: source .venv/bin/activate && isort --check-only .

    - name: black
      if: always()
      run: source .venv/bin/activate && black --check -

    - name: mypy
      if: always()
      run: source .venv/bin/activate && mypy --install-types --non-interactive pytest_tier
